### ISSUE TITLE
Overlapping Components

### ISSUE THREAD

**Issue by Ganesh107** [NCAR/music-box-interactive-client#211]
**Describe the bug**
In the flow diagram section the flow diagram component is overlapped with the footer

**To Reproduce**

1. Go to 'https://musicbox.acom.ucar.edu/'
2. Click on 'Flow Diagram'
3. See error

**Expected behavior**
Flow Diagram component and footer should be seperate (no overlapping)

**Screenshots**
![Screenshot (12)](https://github.com/NCAR/music-box-interactive-client/assets/78807238/032d8b62-c5c7-4ed1-9be2-9109d62151ea)

**Desktop (please complete the following information):**

- OS: windows 10
- Browser: Chrome

**Comment by K20shores** [comment]
@Ganesh107 good catch! Thanks for this

**Comment by Dwayne-B** [comment]
Hello I would like to work on this issue. Could you please assign it to me 😄

**Comment by K20shores** [comment]
@Dwayne-B it's yours! Let me know if you have any questions!

**Comment by K20shores** [comment]
fixed by #223
