### ISSUE TITLE
Initial conditions units

### ISSUE THREAD

**Issue by marybarthbrock** [NCAR/music-box-interactive-client#217]
**Describe the bug**
Could you provide options for initial condition concentrations in ppbv, ppmv, mol/mol

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mattldawson** [comment]
blocked by music-box#236

**Comment by K20shores** [comment]
Closed by #347
