### ISSUE TITLE
Handle Cookies

### ISSUE THREAD

**Issue by shanengys** [NCAR/music-box-interactive-client#22]
Functions that handle cookies.

- [ ] Cookies banner
- [ ] Configure setting for cookies
- [ ] Save and restore cookies to and from browser
- [ ] Cookies-related interactions with the backend server.

**Comment by K20shores** [comment]
Some of this may need to be done (the banner, for GDPR compliance) but much of the functionality of cookies is handled automatically by the browser through HTTP request headers. So, the third and fourth points are probably not necessary
