### ISSUE TITLE
Error returned loading previously saved model configuration

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box-interactive-client#243]
**Describe the bug**
A model configuration saved from a previous run returns an error when trying to reload it

**To Reproduce**

1. Load attached configuration

**Expected behavior**
The configuration is successfully loaded

**Screenshots**
![image](https://github.com/NCAR/music-box-interactive-client/assets/13121557/fb3ea09f-d1d4-48d0-b156-67d52da73763)

**Desktop (please complete the following information):**

- Browser Chrome

**Additional context**
[config.zip](https://github.com/NCAR/music-box-interactive-client/files/14574181/config.zip)

**Comment by K20shores** [comment]
Update: For some reason when the file is loaded into the browsers memory it comes in as a string, not an object.

**Comment by K20shores** [comment]
Update: The evolving conditions file includes these lines at the end:

```
time.s,ENV.pressure.Pa,ENV.temperature.K,PHOT.O2.s-1,PHOT.O3->O1D.s-1,PHOT.O3->O3P.s-1,PHOT.H2O2.s-1,PHOT.NO3->NO2.s-1,PHOT.HNO3.s-1,PHOT.N2O5.s-1,PHOT.NO2.s-1,PHOT.ALD2.s-1,PHOT.FORM->CO.s-1
...
...
...
255600,101300,290,8.74e-39,4.57e-06,0.000279641,2.54e-06,0.0158742,1.43e-07,1.6e-05,0.004517407,9.95e-07,1.85e-05
,,,2.84e-39,1.06e-06,0.000165481,9.87e-07,0.009618972,4.41e-08,6.35e-06,0.002036205,2.68e-07,7.55e-06
,,,5.93e-40,7e-08,9.19e-06,9.63e-08,0.000460242,3.21e-09,6.36e-07,0.000232037,1.57e-08,7.64e-07
,,,0,4.61e-24,1.1e-14,1.41e-20,5.07e-13,1.14e-24,2.32e-19,3.59e-16,4.55e-26,1.62e-21
,,,0,0,0,0,0,0,0,0,0,0
,,,0,0,0,0,0,0,0,0,0,0
,,,0,0,0,0,0,0,0,0,0,0
,,,0,0,0,0,0,0,0,0,0,0
,,,0,0,0,0,0,0,0,0,0,0
,,,0,0,0,0,0,0,0,0,0,0
,,,0,0,0,0,0,0,0,0,0,0
,,,0,0,0,0,0,0,0,0,0,0
,,,,,,,,,,,,
```

When parsed on the server, this leads to the first column, `time.s`, including NaNs, which seems to make parsing the object as a JSON object fail. In any case, deleting the rows after time step `255600` leads to a successful parse

**Comment by SancyW** [comment]
Thanks for your instructions. This should be the reason. However, the new issue is that I can't delete the last row on the evolving page even though it has no value. For example, if I remove the last row, it will produce another NaN row.
![NaN in the evolving page](https://github.com/NCAR/music-box-interactive-client/assets/42404523/494501dc-93b0-4a80-9fe0-d24bae7149ee)

**Comment by SancyW** [comment]
thanks for your hard work

**Comment by SancyW** [comment]
this is another problem
[config.zip](https://github.com/NCAR/music-box-interactive-client/files/14976611/config.zip)
<img width="442" alt="image" src="https://github.com/NCAR/music-box-interactive-client/assets/42404523/8d350585-79df-4358-aa78-415aede13d5d">

**Comment by K20shores** [comment]
@SancyW on the branch for #279 I can upload and run the most recent config you put on this issue. The original config value is not a valid configuration. As for not deleting rows, that's a separate issue

**Comment by K20shores** [comment]
@SancyW, we will close this issue when #279 is merged in but I'll open another issue about the rows not being deletable
