### ISSUE TITLE
Put a github icon somewhere on the page, maybe next to report a bug

### ISSUE THREAD

**Issue by K20shores** [NCAR/music-box-interactive-client#250]

**Comment by ketansahugit** [comment]
Hey @K20shores , just wanted to check: do you want that GitHub icon next to the "Report a bug" button just for looks, or do you want folks to click on it and head straight to the project's GitHub repository? Let me know!

**Comment by K20shores** [comment]
@ketansahugit I think I'd like the github icon to point to [https://github.com/NCAR/music-box-interactive-client](https://github.com/NCAR/music-box-interactive-client) but be beside the report a bug button
