### ISSUE TITLE
Error loading Chapman configuration 

### ISSUE THREAD

**Issue by JoseAgustin** [NCAR/music-box-interactive-client#257]
**Describe the bug**
I try to use the Simplified_Chapman_20km.zip.
but when using it a window indicate to send a notification bug.
**To Reproduce**

1. Go to 'https://github.com/NCAR/musicbox_curriculum_exercises/blob/main/Stratospheric_Mechanisms/Simple_Chapman/Simplified_Chapman_20km.zip'
2. Download the file
3. Goto https://musicbox.acom.ucar.edu/getting_started
4. Click on " Upload configuration file"
5. Select the file "Simplified_Chapman_20km.zip" previously downloaded from GitHub site
6. Click on "Upload"
![FIG1_selectedfile](https://github.com/NCAR/music-box-interactive-client/assets/20843988/9c766870-3b46-431f-b227-a76bf86f9eb1)

8.  A window display the following: 
 Error loading configuration: Request failed with status code 500. If you believe your configuration is valid, please submit a bug at https://github.com/NCAR/music-box-interactive-client/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
![Diplayed Error](https://github.com/NCAR/music-box-interactive-client/assets/20843988/7bbd50b6-b7f1-4442-8060-5b9fcbb25f28)

**Expected behavior**

To display the species in https://musicbox.acom.ucar.edu/mechanism
By using the configuration.zip created in the web page, this problem did not happen 

**Desktop (please complete the following information):**

- OS:  14.4.1 Sonoma
- Browser Safari
- Version 17.4.1 

 
**Additional context**
With 40km does the same
in some cases display  status code 404 or 500.

**Comment by K20shores** [comment]
Thanks for reporting this! We've had some changes with how and where we do parsing since those exercises were last tested. We will look into this.

**Comment by K20shores** [comment]
@JoseAgustin yeah, it appears this is using an older format for the configuration files. We will go through and update all of the example files and ensure they work.

**Comment by K20shores** [comment]
@JoseAgustin I believe I have fixed the configurations and that all of them should work (at least they did for me). Let me know if you have any issues if you are inclined to try them again
