### ISSUE TITLE
Aerosol Phases can't be deleted

### ISSUE THREAD

**Issue by HunterLikeFarmer** [NCAR/music-box-interactive-client#314]
**Describe the bug**
When you add phases into the aerosol phase tab, they can not be deleted. (the reason could be the inappropriate reuse of list component)

**To Reproduce**

1. Go to 'mechanism sidebar section'
2. Click on 'aerosol' tab and then 'phase' tab
3. Add any phases
4. You will be unable to delete the phase by clicking on the cross

**Expected behavior**
It's supposed to be deleted just the way species can be deleted: after deleting, the phase will no appear on the menu and the redux store.

**Screenshots**
![Screenshot 2024-07-23 191227](https://github.com/user-attachments/assets/1070baff-0056-47de-90bb-e506414ac263)

**Comment by nipun-sachintha** [comment]
I have worked on this. fix here https://github.com/NCAR/music-box-interactive-client/pull/318
