### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by HunterLikeFarmer** [NCAR/music-box-interactive-client#315]
**Describe the bug**
You will get a "objects are not valid as a React child" error when you switch tab from aerosol phase to representation, which leads to the crash of the whole page

**To Reproduce**

1. Go to 'sidebar section mechanism '
2. Click on 'Aerosol Phase' tab
3. Add any phase
4. Click on the phase label in the drop-down menu, there should be a detail card on the right
5. Switch to 'Representation' tab, then you will see the error

**Expected behavior**
There shouldn't be such an error

**Screenshots**
![Screenshot 2024-07-23 191942](https://github.com/user-attachments/assets/6987ff73-48dc-417c-96eb-8adfb7f3f1b2)

**Comment by nipun-sachintha** [comment]
I have worked on this. Relevant fix -  https://github.com/NCAR/music-box-interactive-client/pull/316
