### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by K20shores** [NCAR/music-box-interactive-client#99]
**Describe the bug**
On the [mechanisms page](https://musicbox.acom.ucar.edu/mechanism) there are text links to reactions and conditions. Both lead to broken links.

**To Reproduce**
1. Go to [mechanisms page](https://musicbox.acom.ucar.edu/mechanism)
2. Click on 'reactions' or 'model conditions'
3. See a 404 error

**Expected behavior**
- Clicking on 'reactions' navigates to the reactions tab on the mechanism selection section.
- Clicking on 'model conditions' navigates to the conditions section.

**Screenshots**

<img width="865" alt="Screenshot 2023-08-31 at 12 42 58 PM" src="https://github.com/NCAR/music-box-interactive-client/assets/13836216/d42b04a5-4428-4e52-86a8-ccf9969f9757">
<img width="1725" alt="Screenshot 2023-08-31 at 1 34 27 PM" src="https://github.com/NCAR/music-box-interactive-client/assets/13836216/b6d33e1a-ba5a-41ed-9955-b804bac6f0ba">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 116.0.5845.110

**Comment by negar-75** [comment]
Hi @K20shores 
in related to this issue, having macOs is required?because my OS is windows

**Comment by K20shores** [comment]
@negar-75 no, that was just the OS where I observed the issue, but it's present on all platforms
